name: build
on:
  push:
    branches: [ '**' ]
    tags-ignore: [ v* ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Execute build
        run: ./gradlew clean build -x test